-- ==========================================
-- Supabase Database Schema for Sneakers Store
-- HARD RESET VERSION (Drops old tables and recreates them)
-- ==========================================
-- SHOWCASE E-COMMERCE SUPABASE SCHEMA (V2)
-- ==========================================
-- NOTE FOR UPGRADES: If you already have data and just want to add the dual delivery fees (Domicile/Bureau), 
-- do NOT run the DROP TABLE commands. Instead, run only these 4 lines:
--   ALTER TABLE wilaya_fees ADD COLUMN IF NOT EXISTS fee_domicile INTEGER NOT NULL DEFAULT 0;
--   ALTER TABLE wilaya_fees ADD COLUMN IF NOT EXISTS fee_bureau INTEGER NOT NULL DEFAULT 0;
--   UPDATE wilaya_fees SET fee_domicile = fee, fee_bureau = GREATEST(fee - 200, 200) WHERE fee_domicile = 0;
--   NOTIFY pgrst, 'reload schema';
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 0. HARD RESET: Delete all existing tables to avoid cache issues
-- ==========================================
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS sneakers CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS contact_config CASCADE;
DROP TABLE IF EXISTS wilaya_fees CASCADE;

-- ==========================================
-- 1. Categories Table
-- ==========================================
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT UNIQUE NOT NULL,
  name_fr TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  desc_fr TEXT,
  desc_ar TEXT,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. Sneakers Table
-- ==========================================
CREATE TABLE sneakers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT UNIQUE NOT NULL,
  name_fr TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  price INTEGER NOT NULL,
  category_slug TEXT REFERENCES categories(slug) ON DELETE SET NULL,
  image TEXT, 
  sizes INTEGER[] DEFAULT '{}',
  sizes_stock JSONB DEFAULT '{}'::jsonb,
  colorways TEXT[] DEFAULT '{}',
  colors JSONB DEFAULT '[]'::jsonb,
  desc_fr TEXT,
  desc_ar TEXT,
  featured BOOLEAN DEFAULT false,
  is_hot_drop BOOLEAN DEFAULT false,
  is_new_arrival BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. Wilaya Fees Table
-- ==========================================
CREATE TABLE wilaya_fees (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name_fr TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  fee INTEGER NOT NULL,
  fee_domicile INTEGER NOT NULL DEFAULT 0,
  fee_bureau INTEGER NOT NULL DEFAULT 0
);

-- Insert all 69 Algerian Wilayas with dual pricing (domicile & bureau)
INSERT INTO wilaya_fees (id, name_fr, name_ar, fee, fee_domicile, fee_bureau) VALUES
(1, '1 - Adrar', '1 - أدرار', 900, 900, 700),
(2, '2 - Chlef', '2 - الشلف', 500, 500, 300),
(3, '3 - Laghouat', '3 - الأغواط', 700, 700, 500),
(4, '4 - Oum El Bouaghi', '4 - أم البواقي', 600, 600, 400),
(5, '5 - Batna', '5 - باتنة', 600, 600, 400),
(6, '6 - Béjaïa', '6 - بجاية', 500, 500, 300),
(7, '7 - Biskra', '7 - بسكرة', 700, 700, 500),
(8, '8 - Béchar', '8 - بشار', 800, 800, 600),
(9, '9 - Blida', '9 - البليدة', 400, 400, 200),
(10, '10 - Bouira', '10 - البويرة', 500, 500, 300),
(11, '11 - Tamanrasset', '11 - تمنراست', 1200, 1200, 1000),
(12, '12 - Tébessa', '12 - تبسة', 700, 700, 500),
(13, '13 - Tlemcen', '13 - تلمسان', 600, 600, 400),
(14, '14 - Tiaret', '14 - تيارت', 600, 600, 400),
(15, '15 - Tizi Ouzou', '15 - تيزي وزو', 500, 500, 300),
(16, '16 - Alger', '16 - الجزائر', 400, 400, 200),
(17, '17 - Djelfa', '17 - الجلفة', 600, 600, 400),
(18, '18 - Jijel', '18 - جيجل', 600, 600, 400),
(19, '19 - Sétif', '19 - سطيف', 600, 600, 400),
(20, '20 - Saïda', '20 - سعيدة', 600, 600, 400),
(21, '21 - Skikda', '21 - سكيكدة', 600, 600, 400),
(22, '22 - Sidi Bel Abbès', '22 - سيدي بلعباس', 600, 600, 400),
(23, '23 - Annaba', '23 - عنابة', 600, 600, 400),
(24, '24 - Guelma', '24 - قالمة', 600, 600, 400),
(25, '25 - Constantine', '25 - قسنطينة', 600, 600, 400),
(26, '26 - Médéa', '26 - المدية', 500, 500, 300),
(27, '27 - Mostaganem', '27 - مستغانم', 500, 500, 300),
(28, '28 - M''Sila', '28 - المسيلة', 600, 600, 400),
(29, '29 - Mascara', '29 - معسكر', 600, 600, 400),
(30, '30 - Ouargla', '30 - ورقلة', 800, 800, 600),
(31, '31 - Oran', '31 - وهران', 500, 500, 300),
(32, '32 - El Bayadh', '32 - البيض', 700, 700, 500),
(33, '33 - Illizi', '33 - إيليزي', 1000, 1000, 800),
(34, '34 - Bordj Bou Arréridj', '34 - برج بوعريريج', 500, 500, 300),
(35, '35 - Boumerdès', '35 - بومرداس', 400, 400, 200),
(36, '36 - El Tarf', '36 - الطارف', 600, 600, 400),
(37, '37 - Tindouf', '37 - تندوف', 1000, 1000, 800),
(38, '38 - Tissemsilt', '38 - تيسمسيلت', 600, 600, 400),
(39, '39 - El Oued', '39 - الوادي', 800, 800, 600),
(40, '40 - Khenchela', '40 - خنشلة', 700, 700, 500),
(41, '41 - Souk Ahras', '41 - سوق أهراس', 600, 600, 400),
(42, '42 - Tipaza', '42 - تيبازة', 400, 400, 200),
(43, '43 - Mila', '43 - ميلة', 600, 600, 400),
(44, '44 - Aïn Defla', '44 - عين الدفلى', 500, 500, 300),
(45, '45 - Naâma', '45 - النعامة', 700, 700, 500),
(46, '46 - Aïn Témouchent', '46 - عين تموشنت', 600, 600, 400),
(47, '47 - Ghardaïa', '47 - غرداية', 800, 800, 600),
(48, '48 - Relizane', '48 - غليزان', 500, 500, 300),
(49, '49 - Timimoun', '49 - تيميمون', 1000, 1000, 800),
(50, '50 - Bordj Badji Mokhtar', '50 - برج باجي مختار', 1200, 1200, 1000),
(51, '51 - Ouled Djellal', '51 - أولاد جلال', 700, 700, 500),
(52, '52 - Béni Abbès', '52 - بني عباس', 1000, 1000, 800),
(53, '53 - In Salah', '53 - عين صالح', 1200, 1200, 1000),
(54, '54 - In Guezzam', '54 - عين قزام', 1200, 1200, 1000),
(55, '55 - Touggourt', '55 - تقرت', 800, 800, 600),
(56, '56 - Djanet', '56 - جانت', 1200, 1200, 1000),
(57, '57 - El M''Ghair', '57 - المغير', 800, 800, 600),
(58, '58 - El Meniaa', '58 - المنيعة', 800, 800, 600),
(59, '59 - Aflou', '59 - أفلو', 700, 700, 500),
(60, '60 - Barika', '60 - بريكة', 600, 600, 400),
(61, '61 - Ksar Chellala', '61 - قصر الشلالة', 600, 600, 400),
(62, '62 - Messaad', '62 - مسعد', 600, 600, 400),
(63, '63 - Aïn Oussera', '63 - عين وسارة', 600, 600, 400),
(64, '64 - Bou Saâda', '64 - بوسعادة', 600, 600, 400),
(65, '65 - El Abiodh Sidi Cheikh', '65 - الأبيض سيدي الشيخ', 700, 700, 500),
(66, '66 - El Kantara', '66 - القنطرة', 700, 700, 500),
(67, '67 - Bir El Ater', '67 - بئر العاتر', 600, 600, 400),
(68, '68 - Ksar El Boukhari', '68 - قصر البخاري', 600, 600, 400),
(69, '69 - El Aricha', '69 - العريشة', 700, 700, 500)
ON CONFLICT (id) DO UPDATE SET
  name_fr = EXCLUDED.name_fr,
  name_ar = EXCLUDED.name_ar,
  fee = EXCLUDED.fee,
  fee_domicile = EXCLUDED.fee_domicile,
  fee_bureau = EXCLUDED.fee_bureau;

-- Keep the identity sequence aligned with the seeded rows above.
SELECT setval(
  pg_get_serial_sequence('wilaya_fees', 'id'),
  COALESCE((SELECT MAX(id::bigint) + 1 FROM wilaya_fees), 1::bigint),
  false
);

-- ==========================================
-- 4. Leads (Orders) Table
-- ==========================================
CREATE TABLE leads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  wilaya_id INTEGER REFERENCES wilaya_fees(id) ON DELETE SET NULL,
  status TEXT CHECK (status IN ('todo', 'progress', 'delivered')) DEFAULT 'todo',
  notes TEXT,
  tracking_number TEXT,
  shipping_provider TEXT,
  shipped_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 5. Contact & Global Settings Config
-- ==========================================
CREATE TABLE contact_config (
  id INTEGER PRIMARY KEY DEFAULT 1,
  whatsapp TEXT DEFAULT '+213000000000',
  email TEXT DEFAULT 'contact@sneakersobsidian.com',
  hero_banner TEXT,
  site_name TEXT DEFAULT 'SNKRS ALG',
  primary_color TEXT DEFAULT '#00ffcc',
  announcement TEXT DEFAULT 'Welcome to SNKRS ALG! Free shipping on 2+ items.'
);

-- ==========================================
-- 6. Row Level Security (RLS) Policies
-- ==========================================
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE sneakers ENABLE ROW LEVEL SECURITY;
ALTER TABLE wilaya_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Categories are viewable by everyone" ON categories FOR SELECT USING (true);
CREATE POLICY "Categories are insertable by admins" ON categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Categories are updatable by admins" ON categories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Categories are deletable by admins" ON categories FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Sneakers are viewable by everyone" ON sneakers FOR SELECT USING (true);
CREATE POLICY "Sneakers are insertable by admins" ON sneakers FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Sneakers are updatable by admins" ON sneakers FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Sneakers are deletable by admins" ON sneakers FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Wilaya fees are viewable by everyone" ON wilaya_fees FOR SELECT USING (true);
CREATE POLICY "Wilaya fees are insertable by admins" ON wilaya_fees FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Wilaya fees are updatable by admins" ON wilaya_fees FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Wilaya fees are deletable by admins" ON wilaya_fees FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Leads can be created by anyone" ON leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Leads are viewable by admins only" ON leads FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Leads are updatable by admins only" ON leads FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Leads are deletable by admins only" ON leads FOR DELETE USING (auth.role() = 'authenticated');

CREATE POLICY "Contact config viewable by everyone" ON contact_config FOR SELECT USING (true);
CREATE POLICY "Contact config insertable by admins" ON contact_config FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Contact config updatable by admins" ON contact_config FOR UPDATE USING (auth.role() = 'authenticated');

-- ==========================================
-- 7. Triggers
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_sneakers_modtime
BEFORE UPDATE ON sneakers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 8. Enable Realtime
-- ==========================================
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE categories; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE sneakers; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE leads; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER PUBLICATION supabase_realtime ADD TABLE contact_config; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ==========================================
-- 9. Initial Data Seed
-- ==========================================
INSERT INTO contact_config (id, whatsapp, email, site_name, primary_color, announcement)
VALUES (1, '+213000000000', 'contact@sneakersobsidian.com', 'SNKRS ALG', '#00ffcc', 'Welcome to SNKRS ALG! Free shipping on 2+ items.')
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 10. Force Reload Schema Cache
-- ==========================================
NOTIFY pgrst, 'reload schema';
