-- ==========================================
-- Supabase Database Schema for Sneakers Store
-- Safe to re-run (fully idempotent)
-- ==========================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. Categories Table
-- ==========================================
CREATE TABLE IF NOT EXISTS categories (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT UNIQUE NOT NULL,
  name_fr TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  desc_fr TEXT,
  desc_ar TEXT,
  image TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. Sneakers Table
-- ==========================================
CREATE TABLE IF NOT EXISTS sneakers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  slug TEXT UNIQUE NOT NULL,
  name_fr TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  price INTEGER NOT NULL,
  category_slug TEXT REFERENCES categories(slug) ON DELETE SET NULL,
  image TEXT, -- Main sneaker image (URL or Base64 from PC upload)
  sizes INTEGER[] DEFAULT '{}',
  sizes_stock JSONB DEFAULT '{}'::jsonb,
  colorways TEXT[] DEFAULT '{}',
  colors JSONB DEFAULT '[]'::jsonb, -- Array of variant objects: {nameFr, nameAr, hex, image (URL or Base64)}
  desc_fr TEXT,
  desc_ar TEXT,
  featured BOOLEAN DEFAULT false,
  is_hot_drop BOOLEAN DEFAULT false,
  is_new_arrival BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. Wilaya Fees Table
-- ==========================================
CREATE TABLE IF NOT EXISTS wilaya_fees (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name_fr TEXT NOT NULL,
  name_ar TEXT NOT NULL,
  fee INTEGER NOT NULL
);

-- Insert all 58 Algerian Wilayas and their shipping fees
INSERT INTO wilaya_fees (id, name_fr, name_ar, fee) VALUES
(1, '1 - Adrar', '1 - أدرار', 900),
(2, '2 - Chlef', '2 - الشلف', 500),
(3, '3 - Laghouat', '3 - الأغواط', 700),
(4, '4 - Oum El Bouaghi', '4 - أم البواقي', 600),
(5, '5 - Batna', '5 - باتنة', 600),
(6, '6 - Béjaïa', '6 - بجاية', 500),
(7, '7 - Biskra', '7 - بسكرة', 700),
(8, '8 - Béchar', '8 - بشار', 800),
(9, '9 - Blida', '9 - البليدة', 400),
(10, '10 - Bouira', '10 - البويرة', 500),
(11, '11 - Tamanrasset', '11 - تمنراست', 1200),
(12, '12 - Tébessa', '12 - تبسة', 700),
(13, '13 - Tlemcen', '13 - تلمسان', 600),
(14, '14 - Tiaret', '14 - تيارت', 600),
(15, '15 - Tizi Ouzou', '15 - تيزي وزو', 500),
(16, '16 - Alger', '16 - الجزائر العاصمة', 400),
(17, '17 - Djelfa', '17 - الجلفة', 600),
(18, '18 - Jijel', '18 - جيجل', 600),
(19, '19 - Sétif', '19 - سطيف', 600),
(20, '20 - Saïda', '20 - سعيدة', 600),
(21, '21 - Skikda', '21 - سكيكدة', 600),
(22, '22 - Sidi Bel Abbès', '22 - سيدي بلعباس', 600),
(23, '23 - Annaba', '23 - عنابة', 600),
(24, '24 - Guelma', '24 - قالمة', 600),
(25, '25 - Constantine', '25 - قسنطينة', 600),
(26, '26 - Médéa', '26 - المدية', 500),
(27, '27 - Mostaganem', '27 - مستغانم', 500),
(28, '28 - M''Sila', '28 - المسيلة', 600),
(29, '29 - Mascara', '29 - معسكر', 600),
(30, '30 - Ouargla', '30 - ورقلة', 800),
(31, '31 - Oran', '31 - وهران', 500),
(32, '32 - El Bayadh', '32 - البيض', 700),
(33, '33 - Illizi', '33 - إليزي', 1000),
(34, '34 - Bordj Bou Arréridj', '34 - برج بوعريريج', 500),
(35, '35 - Boumerdès', '35 - بومرداس', 400),
(36, '36 - El Tarf', '36 - الطارف', 600),
(37, '37 - Tindouf', '37 - تندوف', 1000),
(38, '38 - Tissemsilt', '38 - تيسمسيلت', 600),
(39, '39 - El Oued', '39 - الوادي', 800),
(40, '40 - Khenchela', '40 - خنشلة', 700),
(41, '41 - Souk Ahras', '41 - سوق أهراس', 600),
(42, '42 - Tipaza', '42 - تيبازة', 400),
(43, '43 - Mila', '43 - ميلة', 600),
(44, '44 - Aïn Defla', '44 - عين الدفلى', 500),
(45, '45 - Naâma', '45 - النعامة', 700),
(46, '46 - Aïn Témouchent', '46 - عين تموشنت', 600),
(47, '47 - Ghardaïa', '47 - غرداية', 800),
(48, '48 - Relizane', '48 - غليزان', 500),
(49, '49 - El M''Ghair', '49 - المغير', 800),
(50, '50 - El Meniaa', '50 - المنيعة', 800),
(51, '51 - Ouled Djellal', '51 - أولاد جلال', 700),
(52, '52 - Bordj Baji Mokhtar', '52 - برج باجي مختار', 1200),
(53, '53 - Béni Abbès', '53 - بني عباس', 1000),
(54, '54 - Timimoun', '54 - تيميمون', 1000),
(55, '55 - Touggourt', '55 - تقرت', 800),
(56, '56 - Djanet', '56 - جانت', 1200),
(57, '57 - In Salah', '57 - عين صالح', 1200),
(58, '58 - In Guezzam', '58 - عين قزام', 1200)
ON CONFLICT (id) DO NOTHING;

-- Keep the identity sequence aligned with the seeded rows above.
SELECT setval(
  pg_get_serial_sequence('wilaya_fees', 'id'),
  COALESCE((SELECT MAX(id::bigint) + 1 FROM wilaya_fees), 1::bigint),
  false
);

-- ==========================================
-- 4. Leads (Orders) Table
-- ==========================================
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  customer_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  wilaya_id INTEGER REFERENCES wilaya_fees(id) ON DELETE SET NULL,
  status TEXT CHECK (status IN ('todo', 'progress', 'delivered')) DEFAULT 'todo',
  notes TEXT,
  tracking_number TEXT,
  shipping_provider TEXT,
  shipped_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 5. Settings / Contact Config Table
-- ==========================================
CREATE TABLE IF NOT EXISTS contact_config (
  id INTEGER PRIMARY KEY DEFAULT 1,
  whatsapp TEXT NOT NULL,
  email TEXT NOT NULL,
  hero_banner TEXT
);

-- Insert initial contact config
INSERT INTO contact_config (id, whatsapp, email)
VALUES (1, '+213000000000', 'contact@sneakersobsidian.com')
ON CONFLICT (id) DO NOTHING;

-- ==========================================
-- 6. Row Level Security (RLS) Policies
-- ==========================================
-- Enable RLS on all tables
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE sneakers ENABLE ROW LEVEL SECURITY;
ALTER TABLE wilaya_fees ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_config ENABLE ROW LEVEL SECURITY;

-- Categories: Public can read, authenticated (Admin) can write
DROP POLICY IF EXISTS "Categories are viewable by everyone" ON categories;
CREATE POLICY "Categories are viewable by everyone" ON categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Categories are insertable by admins" ON categories;
CREATE POLICY "Categories are insertable by admins" ON categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Categories are updatable by admins" ON categories;
CREATE POLICY "Categories are updatable by admins" ON categories FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Categories are deletable by admins" ON categories;
CREATE POLICY "Categories are deletable by admins" ON categories FOR DELETE USING (auth.role() = 'authenticated');

-- Sneakers: Public can read, authenticated (Admin) can write
DROP POLICY IF EXISTS "Sneakers are viewable by everyone" ON sneakers;
CREATE POLICY "Sneakers are viewable by everyone" ON sneakers FOR SELECT USING (true);

DROP POLICY IF EXISTS "Sneakers are insertable by admins" ON sneakers;
CREATE POLICY "Sneakers are insertable by admins" ON sneakers FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Sneakers are updatable by admins" ON sneakers;
CREATE POLICY "Sneakers are updatable by admins" ON sneakers FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Sneakers are deletable by admins" ON sneakers;
CREATE POLICY "Sneakers are deletable by admins" ON sneakers FOR DELETE USING (auth.role() = 'authenticated');

-- Wilaya Fees: Public can read, authenticated (Admin) can write
DROP POLICY IF EXISTS "Wilaya fees are viewable by everyone" ON wilaya_fees;
CREATE POLICY "Wilaya fees are viewable by everyone" ON wilaya_fees FOR SELECT USING (true);

DROP POLICY IF EXISTS "Wilaya fees are insertable by admins" ON wilaya_fees;
CREATE POLICY "Wilaya fees are insertable by admins" ON wilaya_fees FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Wilaya fees are updatable by admins" ON wilaya_fees;
CREATE POLICY "Wilaya fees are updatable by admins" ON wilaya_fees FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Wilaya fees are deletable by admins" ON wilaya_fees;
CREATE POLICY "Wilaya fees are deletable by admins" ON wilaya_fees FOR DELETE USING (auth.role() = 'authenticated');

-- Leads: Public can INSERT, only authenticated (Admin) can view/update/delete
DROP POLICY IF EXISTS "Leads can be created by anyone" ON leads;
CREATE POLICY "Leads can be created by anyone" ON leads FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Leads are viewable by admins only" ON leads;
CREATE POLICY "Leads are viewable by admins only" ON leads FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Leads are updatable by admins only" ON leads;
CREATE POLICY "Leads are updatable by admins only" ON leads FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Leads are deletable by admins only" ON leads;
CREATE POLICY "Leads are deletable by admins only" ON leads FOR DELETE USING (auth.role() = 'authenticated');

-- Contact Config: Public can read, authenticated can update
DROP POLICY IF EXISTS "Contact config viewable by everyone" ON contact_config;
CREATE POLICY "Contact config viewable by everyone" ON contact_config FOR SELECT USING (true);

DROP POLICY IF EXISTS "Contact config updatable by admins" ON contact_config;
CREATE POLICY "Contact config updatable by admins" ON contact_config FOR UPDATE USING (auth.role() = 'authenticated');

-- ==========================================
-- 7. Triggers
-- ==========================================
-- Trigger to automatically update "updated_at" on sneakers table
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_sneakers_modtime ON sneakers;
CREATE TRIGGER update_sneakers_modtime
BEFORE UPDATE ON sneakers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 8. Enable Realtime
-- ==========================================
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE categories;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE sneakers;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE leads;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE contact_config;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ==========================================
-- 9. Migrations / Schema Updates
-- ==========================================
-- Add 'colors' column if it does not exist (for existing tables)
DO $$
BEGIN
  ALTER TABLE sneakers ADD COLUMN colors JSONB DEFAULT '[]'::jsonb;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- ==========================================
-- 10. Reload Schema Cache
-- ==========================================
-- Run this if you just modified the schema directly in SQL Editor
NOTIFY pgrst, 'reload schema';


